version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: audiobook
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
  
volumes:
  user_data: